// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: fsdto.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FsBlockVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginId string `protobuf:"bytes,1,opt,name=originId,proto3" json:"originId,omitempty"`
	Content  []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *FsBlockVo) Reset() {
	*x = FsBlockVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsdto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsBlockVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsBlockVo) ProtoMessage() {}

func (x *FsBlockVo) ProtoReflect() protoreflect.Message {
	mi := &file_fsdto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsBlockVo.ProtoReflect.Descriptor instead.
func (*FsBlockVo) Descriptor() ([]byte, []int) {
	return file_fsdto_proto_rawDescGZIP(), []int{0}
}

func (x *FsBlockVo) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *FsBlockVo) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FsBlockDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref      int32  `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
	OriginId string `protobuf:"bytes,2,opt,name=originId,proto3" json:"originId,omitempty"`
	Content  []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *FsBlockDto) Reset() {
	*x = FsBlockDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsdto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsBlockDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsBlockDto) ProtoMessage() {}

func (x *FsBlockDto) ProtoReflect() protoreflect.Message {
	mi := &file_fsdto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsBlockDto.ProtoReflect.Descriptor instead.
func (*FsBlockDto) Descriptor() ([]byte, []int) {
	return file_fsdto_proto_rawDescGZIP(), []int{1}
}

func (x *FsBlockDto) GetRef() int32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *FsBlockDto) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *FsBlockDto) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UserDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId    string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	NickName  string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatorRef string `protobuf:"bytes,3,opt,name=avatorRef,proto3" json:"avatorRef,omitempty"`
}

func (x *UserDto) Reset() {
	*x = UserDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsdto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDto) ProtoMessage() {}

func (x *UserDto) ProtoReflect() protoreflect.Message {
	mi := &file_fsdto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDto.ProtoReflect.Descriptor instead.
func (*UserDto) Descriptor() ([]byte, []int) {
	return file_fsdto_proto_rawDescGZIP(), []int{2}
}

func (x *UserDto) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserDto) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserDto) GetAvatorRef() string {
	if x != nil {
		return x.AvatorRef
	}
	return ""
}

var File_fsdto_proto protoreflect.FileDescriptor

var file_fsdto_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x73, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x41, 0x0a, 0x09, 0x46, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x54, 0x0a, 0x0a, 0x46, 0x73, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x44, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x5b, 0x0a, 0x07,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x76, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x42, 0x0d, 0x5a, 0x0b, 0x66, 0x61, 0x63,
	0x61, 0x64, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fsdto_proto_rawDescOnce sync.Once
	file_fsdto_proto_rawDescData = file_fsdto_proto_rawDesc
)

func file_fsdto_proto_rawDescGZIP() []byte {
	file_fsdto_proto_rawDescOnce.Do(func() {
		file_fsdto_proto_rawDescData = protoimpl.X.CompressGZIP(file_fsdto_proto_rawDescData)
	})
	return file_fsdto_proto_rawDescData
}

var file_fsdto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fsdto_proto_goTypes = []interface{}{
	(*FsBlockVo)(nil),  // 0: grpc.FsBlockVo
	(*FsBlockDto)(nil), // 1: grpc.FsBlockDto
	(*UserDto)(nil),    // 2: grpc.UserDto
}
var file_fsdto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fsdto_proto_init() }
func file_fsdto_proto_init() {
	if File_fsdto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fsdto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsBlockVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsdto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsBlockDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsdto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fsdto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fsdto_proto_goTypes,
		DependencyIndexes: file_fsdto_proto_depIdxs,
		MessageInfos:      file_fsdto_proto_msgTypes,
	}.Build()
	File_fsdto_proto = out.File
	file_fsdto_proto_rawDesc = nil
	file_fsdto_proto_goTypes = nil
	file_fsdto_proto_depIdxs = nil
}
